redis:
  url: 'localhost:6379/resque:test'
  timeout: 10 # seconds

lybercore_log: 'log/lybercore.log'

# for workflows
workflow:
  url: 'https://workflows.example.org'
  dor_services_url: 'https://fakeuser:fakepass@fakeserver.example.edu/dor'
  logfile: 'log/workflow_service.log'
  shift_age: 'weekly'
  timeout: 60 # seconds

# where to find the deposit bag to be preserved
transfer_object:
  from_host: 'userid@common-accessioning-vm'
  from_dir: '/dor/export/'

ssl:
  # NOTE:  could use cert and key in /etc/pki/tls dir ... w some puppet fun?
  cert_file: 'config/certs/test.crt'
  key_file: 'config/certs/test.key'
  key_pass: ''

moab:
  # storage_roots:
  #   - '/services-disk/store1'
  #   - '/services-disk/store2'
  storage_trunk: 'sdr2objects'
  deposit_trunk: 'deposit'
  path_method: 'druid_tree'

preservation_catalog:
  url: 'http://localhost:3000'
  auth_token: 'eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwcmVzZXJ2YXRpb25fcm9ib3RzIn0.cUW_P2o1eQFImKT4zVSJ9NrctVaE7h8TuBoSEpzPUVH0kQshz6S7XasotboxdmtEJj8kmCwXgr_ZZ6aUCTSCRg'

email_addresses:
  discussion_list: 'user@discussion_list.org'
  user_list: 'user@user_list.org'
